# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDsWv7IMSYdrtaSX4Jhc0EQJ8GXI7wu5
"""

!pip install pdfminer.six
# ✅ Persona-driven Q&A extractor using HuggingFace Transformers
import json
import os
from pdfminer.high_level import extract_text
from transformers import pipeline

qa = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")

persona_questions = {
    "student": [
        "What are the key concepts?",
        "What should I focus on for exams?",
        "Summarize the important points."
    ],
    "researcher": [
        "What methods are used?",
        "What datasets are mentioned?",
        "What future work is suggested?"
    ],
    "teacher": [
        "What are the learning objectives?",
        "What can be taught from this document?",
        "How is this useful for curriculum?"
    ]
}

def extract_text_from_pdf(pdf_path):
    return extract_text(pdf_path)

def extract_answers(text, persona):
    responses = []
    for q in persona_questions.get(persona.lower(), []):
        answer = qa(question=q, context=text)
        responses.append({"question": q, "answer": answer["answer"]})
    return responses

if __name__ == "__main__":
    pdf_file = "/content/sample_data/ai.pdf"
    if not os.path.exists(pdf_file):
        print(f"Error: File not found at {pdf_file}")
    else:
        persona = "researcher"
        context = extract_text_from_pdf(pdf_file)
        answers = extract_answers(context, persona)
        output_filename = f"output_persona_{persona}.json"
        with open(output_filename, "w") as f:
            json.dump(answers, f, indent=4)
        print(f"✅ Round 1B Output saved to {output_filename}")

from google.colab import files
files.download(output_filename)